### ISSUE TITLE
ydim daemontools issue

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ydim#2]
```
@4000000063b1974e1ad2fb44 Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
@4000000063b1974e1fe2123c bundler: failed to load command: ydimd (/home/zdavatz/.rbenv/versions/2.5.0/bin/ydimd)
@4000000063b1974e1fe21a0c TypeError: no implicit conversion of nil into String
@4000000063b1974e1fe21a0c   /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:10:in `join'
@4000000063b1974e1fe21df4   /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:10:in `<class:Server>'
@4000000063b1974e1fe221dc   /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:9:in `<module:YDIM>'
@4000000063b1974e1fe277cc   /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:8:in `<top (required)>'
@4000000063b1974e1fe277cc   /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ydim-1.1.1/lib/ydim/server.rb:6:in `require'
@4000000063b1974e1fe27bb4   /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ydim-1.1.1/lib/ydim/server.rb:6:in `<top (required)>'
@4000000063b1974e1fe2876c   /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ydim-1.1.1/bin/ydimd:7:in `require'
@4000000063b1974e1fe28b54   /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ydim-1.1.1/bin/ydimd:7:in `<top (required)>'
@4000000063b1974e1fe2be1c   /home/zdavatz/.rbenv/versions/2.5.0/bin/ydimd:25:in `load'
@4000000063b1974e1fe2be1c   /home/zdavatz/.rbenv/versions/2.5.0/bin/ydimd:25:in `<top (required)>'
```
this can be solved with: `bundle update --bundler`

**Comment by zdavatz** [comment]
```
`/` is not writable.
@4000000063b197e4234e8554 Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
```
this can be solved with: `bundle update --bundler`

**Comment by zdavatz** [comment]
1. Starting `ydim-html` via daemontools with this setup 
```
#!/bin/sh
exec 2>&1
ulimit -v 10240000
cd /var/www/ydim.ywesee.com/
PATH=/home/zdavatz/.rbenv/versions/2.6.0/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
exec setuidgid zdavatz bundle exec rackup
```
2. resutlts in
```
@4000000063b29a0d1efa0fb4 Parsing options from the first comment line is deprecated!
@4000000063b29a0d2ab697dc RCLConf uses the first existing files of etc/ydim-htmld.yml,/var/ydim/ydim-htmld.yml,/etc/ydim/ydim-htmld.yml
@4000000063b29a0d2ab69fac loaded config from /etc/ydim/ydim-htmld.yml
@4000000063b29a0e107631fc Error loding required libraries no implicit conversion of nil into String
@4000000063b29a0e1076f934 /var/www/ydim.ywesee.com/vendor/ruby/2.7.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:10:in `join'
@4000000063b29a0e1076fd1c /var/www/ydim.ywesee.com/vendor/ruby/2.7.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:10:in `<class:Server>'
@4000000063b29a0e10770104 /var/www/ydim.ywesee.com/vendor/ruby/2.7.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:9:in `<module:YDIM>'
@4000000063b29a0e10770104 /var/www/ydim.ywesee.com/vendor/ruby/2.7.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:8:in `<top (required)>'
@4000000063b29a0e107710a4 /var/www/ydim.ywesee.com/vendor/ruby/2.7.0/gems/ydim-1.1.1/lib/ydim/server.rb:6:in `require'
@4000000063b29a0e1077148c /var/www/ydim.ywesee.com/vendor/ruby/2.7.0/gems/ydim-1.1.1/lib/ydim/server.rb:6:in `<top (required)>'
@4000000063b29a0e1077148c /var/www/ydim.ywesee.com/vendor/ruby/2.7.0/gems/ydim-1.1.1/lib/ydim/invoice.rb:9:in `require'
@4000000063b29a0e10771874 /var/www/ydim.ywesee.com/vendor/ruby/2.7.0/gems/ydim-1.1.1/lib/ydim/invoice.rb:9:in `<top (required)>'
@4000000063b29a0e10772044 /var/www/ydim.ywesee.com/vendor/ruby/2.7.0/gems/ydim-1.1.1/lib/ydim/odba.rb:8:in `require'
@4000000063b29a0e1077242c /var/www/ydim.ywesee.com/vendor/ruby/2.7.0/gems/ydim-1.1.1/lib/ydim/odba.rb:8:in `<top (required)>'
@4000000063b29a0e227f0824 Parsing options from the first comment line is deprecated!
```
3.  Starting in the `/var/www/ydim.ywesee.com` works perfectly with
4. `bundle exec rackup`

**Comment by zdavatz** [comment]
1. Starting `ydim` via daemontools with this setup 
```
#!/bin/sh
exec 2>&1
ulimit -v 10240000
cd /var/www/ydim.ywesee.com/
PATH=/home/zdavatz/.rbenv/versions/2.5.0/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
exec setuidgid zdavatz bundle exec ydimd config=/etc/ydim/ydimd.yml
```
2. results in
```
@4000000063b1d6820b6e27b4 bundler: failed to load command: ydimd (/var/www/ydim.ywesee.com/vendor/ruby/2.5.0/bin/ydimd)
@4000000063b1d6820b76806c /var/www/ydim.ywesee.com/vendor/ruby/2.5.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:10:in `join': no implicit conversion of nil into String (TypeError)
@4000000063b1d6820b76883c 	from /var/www/ydim.ywesee.com/vendor/ruby/2.5.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:10:in `<class:Server>'
@4000000063b1d6820b768c24 	from /var/www/ydim.ywesee.com/vendor/ruby/2.5.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:9:in `<module:YDIM>'
@4000000063b1d6820b768c24 	from /var/www/ydim.ywesee.com/vendor/ruby/2.5.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:8:in `<top (required)>'
@4000000063b1d6820b76de2c 	from /var/www/ydim.ywesee.com/vendor/ruby/2.5.0/gems/ydim-1.1.1/lib/ydim/server.rb:6:in `require'
@4000000063b1d6820b76e214 	from /var/www/ydim.ywesee.com/vendor/ruby/2.5.0/gems/ydim-1.1.1/lib/ydim/server.rb:6:in `<top (required)>'
@4000000063b1d6820b76e214 	from /var/www/ydim.ywesee.com/vendor/ruby/2.5.0/gems/ydim-1.1.1/bin/ydimd:7:in `require'
@4000000063b1d6820b77341c 	from /var/www/ydim.ywesee.com/vendor/ruby/2.5.0/gems/ydim-1.1.1/bin/ydimd:7:in `<top (required)>'
@4000000063b1d6820b773804 	from /var/www/ydim.ywesee.com/vendor/ruby/2.5.0/bin/ydimd:25:in `load'
@4000000063b1d6820b773804 	from /var/www/ydim.ywesee.com/vendor/ruby/2.5.0/bin/ydimd:25:in `<top (required)>'
@4000000063b1d6820b7766e4 	from /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `load'
@4000000063b1d6820b776acc 	from /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `kernel_load'
@4000000063b1d6820b776acc 	from /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:23:in `run'
@4000000063b1d6820b78f93c 	from /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-2.3.26/lib/bundler/cli.rb:486:in `exec'
@4000000063b1d6820b78fd24 	from /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
@4000000063b1d6820b79010c 	from /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
@4000000063b1d6820b7a221c 	from /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
@4000000063b1d6820b7a2604 	from /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-2.3.26/lib/bundler/cli.rb:31:in `dispatch'
@4000000063b1d6820b7b6e24 	from /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
@4000000063b1d6820b7b6e24 	from /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-2.3.26/lib/bundler/cli.rb:25:in `start'
@4000000063b1d6820b7b720c 	from /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-2.3.26/exe/bundle:48:in `block in <top (required)>'
@4000000063b1d6820b7bdf6c 	from /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-2.3.26/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
@4000000063b1d6820b7bdf6c 	from /home/zdavatz/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-2.3.26/exe/bundle:36:in `<top (required)>'
@4000000063b1d6820b7be354 	from /home/zdavatz/.rbenv/versions/2.5.0/bin//bundle:25:in `load'
@4000000063b1d6820b7c2d8c 	from /home/zdavatz/.rbenv/versions/2.5.0/bin//bundle:25:in `<main>'
```
3. Starting in the `/var/www/ydim.ywesee.com` works perfectly with
4. `bundle exec ydimd config=/etc/ydim/ydimd.yml`

**Comment by zdavatz** [comment]
1. With Ruby 3.2.0
2. in `/etc/ydim/svc/run`
```
#!/bin/sh
exec 2>&1
ulimit -v 10240000
cd /var/www/ydim.ywesee.com/
PATH=/home/zdavatz/.rbenv/versions/3.2.0/bin/:/var/www/ydim.ywesee.com/vendor/ruby/3.2.0/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
exec setuidgid zdavatz bundle exec ydimd config=/etc/ydim/ydimd.yml
```
3. The result is:
```
@4000000063b5543c37f42a54 	from /home/zdavatz/.rbenv/versions/3.2.0/bin//bundle:25:in `<main>'
@4000000063b5543d390363ec bundler: failed to load command: ydimd (/var/www/ydim.ywesee.com/vendor/ruby/3.2.0/bin/ydimd)
@4000000063b5543d390b2c1c /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server_config.rb:10:in `join': no implicit conversion of nil into String (TypeError)
@4000000063b5543d390b3004
@4000000063b5543d390b3004     ydim_default_dir = File.join(ENV['HOME'], '.ydim')
@4000000063b5543d390b3004                                  ^^^^^^^^^^^^^^^^^^^^
@4000000063b5543d390b33ec 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server_config.rb:10:in `<class:Server>'
@4000000063b5543d390b33ec 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server_config.rb:9:in `<module:YDIM>'
@4000000063b5543d390bd7fc 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server_config.rb:8:in `<top (required)>'
@4000000063b5543d390bdbe4 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server.rb:6:in `require_relative'
@4000000063b5543d390bdbe4 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server.rb:6:in `<top (required)>'
@4000000063b5543d390ce96c 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/bin/ydimd:7:in `require'
@4000000063b5543d390ced54 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/bin/ydimd:7:in `<top (required)>'
@4000000063b5543d390ced54 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/bin/ydimd:25:in `load'
@4000000063b5543d390d8994 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/bin/ydimd:25:in `<top (required)>'
@4000000063b5543d390d8994 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `load'
@4000000063b5543d390d8d7c 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
@4000000063b5543d390d8d7c 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:23:in `run'
@4000000063b5543d390e8f4c 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli.rb:484:in `exec'
@4000000063b5543d390e9334 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
@4000000063b5543d390e971c 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
@4000000063b5543d390f79ac 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
@4000000063b5543d390f79ac 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in `dispatch'
@4000000063b5543d39106bdc 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
@4000000063b5543d39106fc4 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in `start'
```

**Comment by zdavatz** [comment]
![Bildschirm­foto 2023-01-04 um 11 31 52](https://user-images.githubusercontent.com/4953/210536114-ed1c3827-7254-4ae6-9c61-217f0970a8c1.png)

**Comment by zdavatz** [comment]
```
@4000000063b555e23acf233c /usr/bin/env: 'ruby231': No such file or directory
@4000000063b555e400aa6324 /usr/bin/env: 'ruby231': No such file or directory
@4000000063b555e502a6852c /usr/bin/env: 'ruby231': No such file or directory
@4000000063b555ef1e55a9c4 /usr/bin/env: 'ruby231': No such file or directory
@4000000063b555f01e0d4a6c /usr/bin/env: 'ruby231': No such file or directory
@4000000063b555f11f446adc /usr/bin/env: 'ruby231': No such file or directory
@4000000063b555f220d36f4c /usr/bin/env: 'ruby231': No such file or directory
@4000000063b555f325106934 /usr/bin/env: 'ruby231': No such file or directory
@4000000063b555f4241330fc /usr/bin/env: 'ruby231': No such file or directory
@4000000063b555f525b8c2dc /usr/bin/env: 'ruby231': No such file or directory
@4000000063b555f626c139fc /usr/bin/env: 'ruby231': No such file or directory
@4000000063b555f727627b3c /usr/bin/env: 'ruby231': No such file or directory
@4000000063b555f82936c60c /usr/bin/env: 'ruby231': No such file or directory
@4000000063b555f92aacb49c /usr/bin/env: 'ruby231': No such file or directory
```

**Comment by ngiger** [comment]
Okay. Einen Fehler habe ich gesehen. Die erste Zeile im bin/ydimd heisst 
`#!/usr/bin/env ruby231`
Deshalb startet es nicht auf. Eventuell würde es mit `#!/usr/bin/env ruby-230` besser gehen.

**Comment by zdavatz** [comment]
Machst Du einen neuen Commit?

**Comment by ngiger** [comment]
Schon gemacht für ydim-html mit neuem bin/ydimd.
Aber man sollte wie folgt starten `bundle exec ruby<-version> bin/ydim`, falls  ẁhich ruby` nicht auf die richtige Ruby-Version zeigt.

**Comment by zdavatz** [comment]
```
@4000000063b55e881e08aebc /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server_config.rb:10:in `join': no implicit conversion of nil into String (TypeError)
@4000000063b55e881e08b68c
@4000000063b55e881e08b68c     ydim_default_dir = File.join(ENV['HOME'], '.ydim')
@4000000063b55e881e08b68c                                  ^^^^^^^^^^^^^^^^^^^^
@4000000063b55e881e08b68c 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server_config.rb:10:in `<class:Server>'
@4000000063b55e881e08ba74 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server_config.rb:9:in `<module:YDIM>'
@4000000063b55e881e09cfcc 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server_config.rb:8:in `<top (required)>'
@4000000063b55e881e09cfcc 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server.rb:6:in `require_relative'
@4000000063b55e881e09d3b4 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server.rb:6:in `<top (required)>'
@4000000063b55e881e0a3944 	from bin/ydimd:7:in `require'
@4000000063b55e881e0a3944 	from bin/ydimd:7:in `<main>'
^C
```

**Comment by ngiger** [comment]
Release ydim gem 1.1.3

**Comment by zdavatz** [comment]
This now works:
```
#!/bin/sh
exec 2>&1
ulimit -v 10240000
cd /var/www/ydim.ywesee.com/
PATH=/home/zdavatz/.rbenv/versions/3.2.0/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
exec setuidgid zdavatz bundle exec bin/ydimd config=/etc/ydim/ydimd.yml
```
