### ISSUE TITLE
After fixing #19 error `failed to load command: bin/ydimd (bin/ydimd)` appears

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ydim#7]
```
@4000000063cc0d622bfb4124 bundler: failed to load command: bin/ydimd (bin/ydimd)
@4000000063cc0d622c00dea4 /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:10:in `join': no implicit conversion of nil into String (TypeError)
@4000000063cc0d622c00e28c
@4000000063cc0d622c00e28c     ydim_default_dir = File.join(ENV['HOME'], '.ydim')
@4000000063cc0d622c00e674                                  ^^^^^^^^^^^^^^^^^^^^
@4000000063cc0d622c00e674       from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:10:in `<class:Server>'
@4000000063cc0d622c00e674       from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:9:in `<module:YDIM>'
@4000000063cc0d622c00fde4       from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:8:in `<top (required)>'
@4000000063cc0d622c00fde4       from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/server.rb:6:in `require'
@4000000063cc0d622c0101cc       from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/server.rb:6:in `<top (required)>'
```

**Comment by zdavatz** [comment]
The problem seems to sit here: https://github.com/zdavatz/ydim-html/blob/master/lib/ydim/html/config.rb#L10

**Comment by zdavatz** [comment]
The problem in in `ydim-html`, so closing this.

**Comment by zdavatz** [comment]
Problem also seems to be here: https://github.com/zdavatz/ydim/blob/master/lib/ydim/config.rb#L10
and here: https://github.com/zdavatz/ydim/blob/master/lib/ydim/server_config.rb#L10

**Comment by zdavatz** [comment]
Default `ydimd.yml` directory is here: `/etc/ydim/ydimd.yml`
Default `ydim.yml` directory is here: `/etc/ydim/ydim.yml`

**Comment by zdavatz** [comment]
this was needed as well: https://github.com/zdavatz/ydim/commit/29932db55610d78c5ffc71e0af6d26cdaf64def2
